### ISSUE TITLE
32位系统不支持吗？

### ISSUE THREAD

**Issue by Alvin9999** [ShadowsocksR-Live/overtls#14]
hi，看了软件的下载列表，目前没有32位软件，请问这个之后会考虑增加32位软件吗？还是有一些用户的电脑是32位系统，如果只有64位的，那么他们就不能体验这款工具了。

**Comment by ssrlive** [comment]
由于使用 32 位机子用户很少, 此前还没人提出要求, 既然有人提, 那就加上吧.

**Comment by Alvin9999** [comment]
能用这款软件就行。32位软件，32位系统用户和64系统用户都能使用。

**Comment by Alvin9999** [comment]
感谢！
