### ISSUE TITLE
使用服务器脚本安装，卡在了输入域名后 Obtaining public IP information, please wait patiently 的选项

### ISSUE THREAD

**Issue by d4rkblue** [ShadowsocksR-Live/overtls#18]
具体表现为出现第二次%Totle ... 的提示后，Time spent 增加，但是没有动静。
VPS 是debian11 64 位的，域名正确解析。
请问如何处理

**Comment by ssrlive** [comment]
你的主机是IPv4 还是第一IPv6 还是双栈的？

如果是双栈的时候请停用来IPv6

**Comment by d4rkblue** [comment]
IPv4，IPv6禁用了。回复消息的刚才，已经OK了。抱歉，我没等足够的时间，问题已经解决。

**Comment by ssrlive** [comment]
Please wait patiently 的意思就是 耐心等待
