### ISSUE TITLE
能docker部署吗 请提供镜像谢谢

### ISSUE THREAD

**Issue by chenxudong2020** [ShadowsocksR-Live/overtls#19]
如题

**Comment by ssrlive** [comment]
对 docker 不熟，你能提供帮助吗？

**Comment by chenxudong2020** [comment]
可以 我有时间 写个提交

**Comment by chenxudong2020** [comment]
> 对 docker 不熟，你能提供帮助吗？

# overtls
docker run --restart always -p 80:80 -p 443:443  --name overtls -e TUNNEL_PATH=/secret-tunnel-path/ -v /cert:/cert -v /web:/web -itd registry.cn-hangzhou.aliyuncs.com/dubux/overtls:latest

# 参数说明
-v 证书所在目录 一定要映射到/cert容器目录 证书要目录中必须存在私钥privkey.pem 公钥fullchain.pem 名字不对请该名
-v web静态文件所在目录 其中必须为包含index.php index.html index.htm index.nginx-debian.html 任何一个为默认首页 请自己从网上下载之后放入目录重启容器或者新建容器提前放好，映射之后的容器的目录必须是/web
-e TUNNEL_PATH 默认为 /secret-tunnel-path/ 请修改 否则出现任何后果自负

**Comment by chenxudong2020** [comment]
我想请问 如果客户端都配置好了 怎么判断走了overtls通道 windows下启动客户端是在cmd中启动的也没打印日志 因为我只有内地的服务器 没有外面的服务器 所以无法测试出国功能

**Comment by ssrlive** [comment]
我客戶端啓動 overtls 的命令是這個， 
```
overtls.exe -c D:\cfg.json -v trace
```
這個 `-v` 參數帶 `trace` 選項就可以打印所有輸出。

**Comment by ssrlive** [comment]
檢驗是否起作用，可以使用 `curl` 取 百度網頁。
```
curl --proxy socks5h://127.0.0.1:1080 https://baidu.com
```
這裏 127.0.0.1:1080 是 overtls 客戶端的本地監聽端口。

**Comment by ssrlive** [comment]
我客戶端啓動 overtls 的命令是這個，
```
overtls.exe -c D:\cfg.json -v trace
```
這個 -v 參數帶 trace 選項就可以打印所有輸出。

檢驗是否起作用，可以使用 curl 取 百度網頁。
```
curl --proxy socks5h://127.0.0.1:1080 https://baidu.com
```
這裏 127.0.0.1:1080 是 overtls 客戶端的本地監聽端口。查看 overtls 和 curl 命令的輸出。就可以判斷安裝是否成功。

**Comment by ssrlive** [comment]
overtls 沒有內建 根據 ip 是中國還是 美國 走代理還是不走代理這種分流。那樣就與 overtls 這個極簡主義的翻牆軟件的設計理念不符啊。

**Comment by chenxudong2020** [comment]
道理我知道，我的意思本地做分流 如果是国外的域名或者ip走 over tls 否则直连 一方面1降低被发现，2降低服务器流量
只需要在客户端进行处理 服务器端不用改动



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月17日(周三) 晚上10:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ShadowsocksR-Live/overtls] 能docker部署吗 请提供镜像谢谢 (Issue #19)




 
overtls 沒有內建 根據 ip 是中國還是 美國 走代理還是不走代理這種分流。那樣就與 overtls 這個極簡主義的翻牆軟件的設計理念不符啊。

**Comment by ssrlive** [comment]
其實你說的與我說的是一碼事，沒做這個就是不想將軟件功能做得太複雜。
其實 微軟瀏覽器 加 `SwitchyOmega` 插件就能達到目的。

![image](https://github.com/ShadowsocksR-Live/overtls/assets/30760636/59c6a3f5-b7fb-40b7-9af9-4d439a3641a4)

![image](https://github.com/ShadowsocksR-Live/overtls/assets/30760636/58a618c5-03c0-49da-9516-8f83cef4a499)

**Comment by ssrlive** [comment]
過濾網站列表在這裏  https://gist.github.com/ssrlive/0ffdb7c430ab865c0bff82a5fe5a296e

**Comment by chenxudong2020** [comment]
这个我在用，无法做自动， 我觉得可以把客户端做成单独的项目 客户端做分流可以参考下一些现有开源项目，好像clash等项目就可以本地分流，把他们集成到over tls客户端



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月17日(周三) 晚上11:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ShadowsocksR-Live/overtls] 能docker部署吗 请提供镜像谢谢 (Issue #19)




 
其實你說的與我說的是一碼事，沒做這個就是不想將軟件功能做得太複雜。
 其實 微軟瀏覽器 加 SwitchyOmega 插件就能達到目的。
 
image.png (view on web)
 
image.png (view on web)

**Comment by chenxudong2020** [comment]
证书可以用openssl自签名的证书吗 我完善下docker如果不提供证书 则内部生成自签名的证书

**Comment by ssrlive** [comment]
理論上是可以，但 GFW 那裏能否通過就難說了， 可以試試自簽名證書的網站在瀏覽器中打開，各種警告不服。
可以先試驗一把。

**Comment by chenxudong2020** [comment]
那就不加了 万一有人出了问题还得背锅 当前没有证书是无法启动的。。。。。。

**Comment by chenxudong2020** [comment]
> 其實你說的與我說的是一碼事，沒做這個就是不想將軟件功能做得太複雜。 其實 微軟瀏覽器 加 插件就能達到目的。`SwitchyOmega`
> 
> ![image](https://private-user-images.githubusercontent.com/30760636/297420368-59c6a3f5-b7fb-40b7-9af9-4d439a3641a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjYxMTksIm5iZiI6MTcwNTcyNTgxOSwicGF0aCI6Ii8zMDc2MDYzNi8yOTc0MjAzNjgtNTljNmEzZjUtYjdmYi00MGI3LTlhZjktNGQ0MzlhMzY0MWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA0NDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZTA2ZDdhMDBhNjk1MmM0YWQwMDUzMTRjODQxN2U1YjY2ZDU1OGI2NjZjMzAzMmMwYmU5MWM2OWM4ODhhMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nW73mpw34dd3XgD6Qtan6dWAf-Li73iLXm6Vty2cVnQ)
> 
> ![image](https://private-user-images.githubusercontent.com/30760636/297420926-58a618c5-03c0-49da-9516-8f83cef4a499.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjYxMTksIm5iZiI6MTcwNTcyNTgxOSwicGF0aCI6Ii8zMDc2MDYzNi8yOTc0MjA5MjYtNThhNjE4YzUtMDNjMC00OWRhLTk1MTYtOGY4M2NlZjRhNDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA0NDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYmNlNmJiZWNhYWU4OGQwNjY4MjlmZDAzNTkxMzMyOTY5M2MxNDczOTRiMTU2ZGIwMTI4MzFkNmRiMzY4YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uDC8qHXh4cp87VBSgUvGPtehXCQOyMNZElJYj0IKt7A)

手机端我看了有功能设置  路由 里面有设置 我说的功能可以再ssrWin中提供 不知道有计划吗

**Comment by ssrlive** [comment]
這裏有個程序 [http2socks](https://github.com/cssivision/http2socks) , 可以替換 ssrWin 裏裝配的 privoxy 組件，在這個 http2socks 程序上開個口子過濾目標網址進行分流，就能達到目的，如果你有興趣，可以搞着玩。當然得會 rust 編程語言。

**Comment by chenxudong2020** [comment]
额😓我不会rust语言



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月20日(周六) 下午3:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ShadowsocksR-Live/overtls] 能docker部署吗 请提供镜像谢谢 (Issue #19)




 
這裏有個程序 http2socks , 可以替換 ssrWin 裏裝配的 privoxy 組件，在這個 http2socks 程序上開個口子過濾目標網址進行分流，就能達到目的，如果你有興趣，可以搞着玩。當然得會 rust 編程語言。
