### ISSUE TITLE
tungstenite::error::Error WebSocket protocol 

### ISSUE THREAD

**Issue by zerodwide** [ShadowsocksR-Live/overtls#20]
Greetings!
I'm getting alot of this error on both server and client usually when trying to ping test!
with nginx or without it, with tls on or off!

i should mention that everythings works great in browsing or youtube watching! but just want to know may that error occure sometimes more that may i'm not aware of.

client error:
`
overtls::client] 127.0.0.1:35182 <> www.google.com:443 tungstenite::error::Error WebSocket protocol error: Connection reset without closing handshake
`

server error:
`
overtls::server] 142.251.1.188:5228 ws_stream_to_outgoing "tungstenite::error::Error WebSocket protocol error: Connection reset without closing handshake"
`

**Comment by ssrlive** [comment]
This is normal. There will always be some connections that will be
interrupted unexpectedly. At this time, the websocket protocol will not
have a chance to be fully implemented. This happens at this time.  This
does not affect the use,

**Comment by ssrlive** [comment]
New version have fixed this issue.
