### ISSUE TITLE
tokio-tungstenite master库不兼容更新了

### ISSUE THREAD

**Issue by a365344743s** [ShadowsocksR-Live/overtls#23]
遇到编译问题的伙伴需要指定tokio-tungstenite版本
![image](https://github.com/ShadowsocksR-Live/overtls/assets/15245246/8e88c764-bf03-4550-af4f-377e9c0d3ba4)

**Comment by ssrlive** [comment]
不知道你編譯的是哪個版本. 我這裏沒問題.
![image](https://github.com/ShadowsocksR-Live/overtls/assets/30760636/c04bb52a-6a76-4a05-9f91-a92de2fc9055)

**Comment by a365344743s** [comment]
我看到master代码是指定了的，不知为什么我的HEAD没有拉下来最新的节点，而是指向了 882892e这个节点。
<img width="1246" alt="image" src="https://github.com/ShadowsocksR-Live/overtls/assets/15245246/7f3c5efc-0562-483e-8adb-332fa60457b2">
