### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by hdid** [ShadowsocksR-Live/overtls#24]
what is this error (when running)
```
[2023-07-05T21:01:33Z INFO  overtls::server] starting overtls server...
thread 'main' panicked at 'removal index (is 0) should be < len (is 0)', /project/src/server.rs:70:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
server is ubuntu 22.04.1 x64

**Comment by ssrlive** [comment]
It is evident that the key file you provided is incorrect. The server was unable to parse it correctly.

**Comment by ssrlive** [comment]
you can clone the source code again and build / run / test it.

**Comment by zheshinicheng** [comment]
我想你们应该尝试一下这个项目[acme.sh](https://github.com/acmesh-official/acme.sh)。
可以自动化签发并续约SSL证书，并且是免费，开源的。
**另外你们需要注意的是overtls这个项目使用X509证书，而acme.sh默认签发EC证书**
` -k, --keylength <bits>            Specifies the domain key length: 2048, 3072, 4096, 8192 or ec-256, ec-384, ec-521.`
`签发证书时避免选择ec-256, ec-384, ec-521` @ssrlive @hdid

**Comment by ssrlive** [comment]
you must use `private_key.pem` file
