### ISSUE TITLE
m1和 m2电脑 能正常编译吗？为啥我报错了

### ISSUE THREAD

**Issue by guangjianzhou** [ShadowsocksR-Live/overtls#36]

**Comment by guangjianzhou** [comment]
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-apple-ios` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-apple-ios`

error[E0463]: can't find crate for `compiler_builtins`

error[E0463]: can't find crate for `alloc`

**Comment by guangjianzhou** [comment]
rustup target add aarch64-apple-ios  这个 我安装了啊

**Comment by ssrlive** [comment]
估計你編譯時, 也得帶上 那個 參數.
