### ISSUE TITLE
用脚本安装overtls，脚本申请的证书没有子域名

### ISSUE THREAD

**Issue by Nesisummer** [ShadowsocksR-Live/overtls#37]
安装ssrot时，在letsencrypt网站上能查询到*.xxx.com与xxx.com的申请记录，但是安装overtls就没有申请子域名了

**Comment by ssrlive** [comment]
因爲 多添加一個 子域名（如： www），經常造成用戶的理解、輸入錯誤，於是在編寫新腳本時，只指定一個確定的全域名了。
你如果只有一個掛在別的域名下的子域名，你就把它全部輸入進去吧。

**Comment by Nesisummer** [comment]
明白了，感谢
