### ISSUE TITLE
socks5端口如何增加名和密的验证....

### ISSUE THREAD

**Issue by liker5092** [ShadowsocksR-Live/overtls#39]
一直在关注！！！

**Comment by ssrlive** [comment]
想了一下, 你其实是不想你局域网里的同事蹭你的梯子, 这就是防君子不防小人. 加上了. 不过够猥琐.

https://github.com/ShadowsocksR-Live/overtls/blob/1856e3e7798b55bc284f00303045f20e912062bb/config.json#L28-L29
