### ISSUE TITLE
[Suggestion] TUNNEL_ PATH supports multiple path splitting strings

### ISSUE THREAD

**Issue by chenxudong2020** [ShadowsocksR-Live/overtls#45]
[Suggestion] TUNNEL_ PATH supports multiple path splitting strings
Would this be more like visiting a normal website and using a random algorithm to load it locally

**Comment by ssrlive** [comment]
multi-path supported. please test it. 
https://github.com/ShadowsocksR-Live/overtls/tree/multipath

**Comment by chenxudong2020** [comment]
Could you please release a version

**Comment by chenxudong2020** [comment]
I know how to compile and have time to test it. I have already created a Docker image using Overtls as a client and Singbox in conjunction with pre porting. If you have time to experience it, I have thought about it. If Overtls does have some functions that are duplicated with other software, there may be unsafe issues. For example, if Bilibili detects a VPS proxy, it may determine that it is in FQ. If there is a need, you can temporarily use Singbox in conjunction with it. You can refer to my code repository: https://github.com/chenxudong2020/overtlsclient

**Comment by chenxudong2020** [comment]
multiple forms are /user, user2,user3/ also/user/, /user2/, /user3/  ?

**Comment by ssrlive** [comment]
```json
{
    "tun_path":["/secret-tunnel-path1/", "/secret-tunnel-path2/", "/secret-tunnel-path3/"],
    // ...
}
```

**Comment by chenxudong2020** [comment]
There were no issues with the testing, and in the future, I will modify Docker to support this feature
