### ISSUE TITLE
Is overtls exposed as the client version of socks5? If so, socks5 does not support UDP？

### ISSUE THREAD

**Issue by chenxudong2020** [ShadowsocksR-Live/overtls#47]
When using overtls as a client, does it expose the version of socks5?
If so, socks5 can support UDP testing.
When using overtls as a client, it does not support UDP

**Comment by ssrlive** [comment]
```
cargo install socks5-impl --example udp-client
```
```
udp-client -h
Udp client through socks5 proxy

Usage: udp-client [OPTIONS] --target-addr <addr:port> --data <data>

Options:
  -t, --target-addr <addr:port>  Udp target server address
  -d, --data <data>              Data string to send
  -v, --via-proxy                Via socks5 proxy server
  -p, --proxy-addr <addr:port>   Socket5 proxy server address
  -u, --username <user name>     User name for authentication
  -w, --password <password>      Password for authentication
  -m, --timeout <seconds>        Timeout in seconds [default: 2]
  -h, --help                     Print help
  -V, --version                  Print version
```

```
udp-client -t udp_server_ip:port -d testdada -v -p 127.0.0.1:1080
```

**Comment by chenxudong2020** [comment]
> ```
> cargo install socks5-impl --example udp-client
> ```
> 
> ```
> udp-client -h
> Udp client through socks5 proxy
> 
> Usage: udp-client [OPTIONS] --target-addr <addr:port> --data <data>
> 
> Options:
>   -t, --target-addr <addr:port>  Udp target server address
>   -d, --data <data>              Data string to send
>   -v, --via-proxy                Via socks5 proxy server
>   -p, --proxy-addr <addr:port>   Socket5 proxy server address
>   -u, --username <user name>     User name for authentication
>   -w, --password <password>      Password for authentication
>   -m, --timeout <seconds>        Timeout in seconds [default: 2]
>   -h, --help                     Print help
>   -V, --version                  Print version
> ```
> 
> ```
> udp-client -t udp_server_ip:port -d testdada -v -p 127.0.0.1:1080
> ```

感谢 已经实现了overtls和sing-box联用 并实现了分流

**Comment by chenxudong2020** [comment]
https://github.com/chenxudong2020/overtlsclient
