### ISSUE TITLE
NAT 主机启动overtls报错 详细日志见图片

### ISSUE THREAD

**Issue by chenxudong2020** [ShadowsocksR-Live/overtls#53]
![image](https://github.com/ShadowsocksR-Live/overtls/assets/61214170/13ffce8e-4ca7-41b1-b381-107d5b930c7d)
 ERROR overtls] IO error: Address not available (os error 99)

系统是debain 12 x84 overtls版本是最新发行版本

**Comment by ssrlive** [comment]
NAT 主機， 地址無效，這真搞不定。估計是你本機的 IP 地址沒配好。

**Comment by chenxudong2020** [comment]
就是nat服务器 免费送的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月14日(周日) 晚上8:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ShadowsocksR-Live/overtls] NAT 主机启动overtls报错 详细日志见图片 (Issue #53)




 
NAT 主機， 地址無效，這真搞不定。估計是你本機的 IP 地址沒配好。

**Comment by ssrlive** [comment]
你會 gdb 調試嗎？可以單步跟蹤到底在哪裏出問題。然後在這裏報告。
```
git clone https://github.com/ShadowsocksR-Live/overtls.git
cd overtls
cargo b
gdb --args ./target/debug/overtls -r server -c /data/apps/overtls/config.json -v trace
```
在main 函數那裏設置斷點 `break server.rs:34` 後，執行 `run` 命令後就會斷下來，執行 `next` 命令就可以一步一步的觀察執行情況了。
如果要進入某個函數內部，就用 `step` 命令。

**Comment by chenxudong2020** [comment]
服務器的問題重裝了系統 已經好了,不過NAT的情況下 用overtls做代理服務器 nginx做http服務器
