### ISSUE TITLE
Is service secured? or just using obfuscation?

### ISSUE THREAD

**Issue by snapshotleisure** [ShadowsocksR-Live/overtls#59]
Hi,

Great piece of software! I just wanted to check something to make sure I have the correct understanding of the setup. 

Is the overtls server secured in the sense there has to be authentication with the client? If so what is the authentication mechanism?

Currently from what I think I can see, there is no authentication as such, but more obfuscation via the tunnel secret? If someone else had the tunnel secret, would they be able to access my instance of overtls by configuring their client with the same tunnel secret?

Just wanted to understand, as I was thinking of adding my overtls server as a exit node for tailscale, but wanted to make sure I wasn't unknowingly exposing my internal services out

Thank you!

**Comment by ssrlive** [comment]
Overtls has no authentication and is designed to fool GFW censorship. 
A complex "tunnel_path" value can effectively prevent strangers from stealing your service.

**Comment by snapshotleisure** [comment]
Hi @ssrlive 

Ok thank you very much for confirming!
