### ISSUE TITLE
是否所有流量走代理，YT 视频和网页正常，命令行下载经常速度很慢

### ISSUE THREAD

**Issue by videosoftware** [ShadowsocksR-Live/overtls#62]
我很喜欢 overtls 的极简主义理念

目前使用 ssrWin GUI 客户端，看 YT 1080P 视频 没问题，但是命令行下载，如编程语言包管理器从 github 下载包，scoop  命令行安装软件等，时常遇到速度很慢甚至连接不上

我的疑问是，使用 ssRWin 时，是否所有流量走代理，还是有些情况，如命令行程序要手动设置代理？

我听说 clash 可以开启接管全部流量，不过，我喜欢 overtls 的简洁，希望能找原因，解决问题

我曾尝试在开启 ssRWin 代理后，给 git 全局配置代理，没有成功，配置后就连不上

---

为了排除是路由器的问题，我让电脑连上手机热点，电脑开启 ssrWin，打开网页没问题，运行 scoop  显示同样的问题：

```bash
$ scoop update git
Updating Scoop...
fatal: unable to access 'https://github.com/lukesampson/scoop/': Could not resolve host: github.com
Update failed.

```

**Comment by ssrlive** [comment]
你得配合 https://github.com/tun2proxy/tun2proxy 食用，它專門幹這個的。

**Comment by videosoftware** [comment]
感谢提示，困扰多日的问题终于解决。现在命令行下载包的速度很快了
