### ISSUE TITLE
How to use Caddy to replace nginx

### ISSUE THREAD

**Issue by chenxudong2020** [ShadowsocksR-Live/overtls#65]
How to use Caddy instead of nginx, it can automatically apply for certificates ,Can you help me?

**Comment by ssrlive** [comment]
I try to write a `Caddyfile` but it not works. can you resolve it?
```caddy
mysite.com:443 {
    tls a@gmail.com
    encode gzip

    handle_path /mypathYWiWL* {
        reverse_proxy 127.0.0.1:12948
    }
    handle {
        reverse_proxy https://www.gov.cn {
            trusted_proxies 0.0.0.0/0
            header_up Host {upstream_hostport}
        }
    }
}
```

**Comment by ssrlive** [comment]
And this settings not work also:
```caddy
fspaceinc.com:443 {
    tls s@gmail.com
    encode gzip

    handle_path /mypathWiWL/* {
        reverse_proxy http://127.0.0.1:12948 {
            header_up Host {host}
            header_up X-Real-IP {remote}
            header_up X-Forwarded-For {remote}
            header_up X-Forwarded-Proto {scheme}
            header_up Upgrade {upstream_upgrade}
            header_up Connection {upstream_connection}
        }
    }

    handle {
        reverse_proxy https://www.gov.cn {
            trusted_proxies 0.0.0.0/0
            header_up Host {upstream_hostport}
        }
    }
}
```

**Comment by chenxudong2020** [comment]
I tried the key point that nginx supports websocket configuration and converted it to caddy, but found it to be an old error. I am not familiar with caddy and only want to use its automatic certificate application to configure multi domain sharing 443. However, I found that it does not work and can only wait for someone familiar with it to improve. Recently, I found that the previous nginx configuration also reported an error, and I am not sure if it is due to overtls upgrade

**Comment by ssrlive** [comment]
Now `overtls` can work with `Caddy`, the `Caddyfile` likes
```caddy
mysite.com:443 {
    tls s@gmail.com
    encode gzip

    reverse_proxy /mypathWiWL/* 127.0.0.1:12456

    reverse_proxy https://www.sohu.com {
        trusted_proxies 0.0.0.0/0
        header_up Host {upstream_hostport}
    }
}
```
Hope somebody can write an installation script.

**Comment by chenxudong2020** [comment]
> Now `overtls` can work with `Caddy`, the `Caddyfile` likes
> 
> ```Caddyfile
> mysite.com:443 {
>     tls s@gmail.com
>     encode gzip
> 
>     reverse_proxy /mypathWiWL/* 127.0.0.1:12456
> 
>     reverse_proxy https://www.sohu.com {
>         trusted_proxies 0.0.0.0/0
>         header_up Host {upstream_hostport}
>     }
> }
> ```
> 
> Hope somebody can write an installation script.
> 
> Caddy installation script
> 
> ```shell
> sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https curl
> curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
> curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
> sudo apt update
> sudo apt install caddy
> ```

I found an error during testing, and I am using the latest version v0.2.37
![image](https://github.com/user-attachments/assets/20654f5e-5831-4094-b357-3f074a497f07)
[2024-10-05 18:07:59 TRACE overtls::udprelay] - [UDP] String error: Response { status: 200, version: HTTP/1.1, headers: {"alt-svc": "h3=\":443\"; ma=2592000", "server": "Caddy", "date": "Sat, 05 Oct 2024 10:08:08 GMT", "content-length": "0"}, body: None }
[2024-10-05 18:08:00 TRACE overtls::udprelay] - [UDP] udp client guard thread exited
[2024-10-05 18:08:00 TRACE overtls::udprelay] - [UDP] udp client guard thread started
At this time, proxy internet access is also not allowed

**Comment by ssrlive** [comment]
Caddy not support using IP as host name. so you must provide a domain name for your config file.

![image](https://github.com/user-attachments/assets/8230a4c0-67e6-468a-ab4d-80747c5bb74c)

**Comment by chenxudong2020** [comment]
![image](https://github.com/user-attachments/assets/6a5b99a5-7195-41d2-8e38-7ff33049eef1)
I don't know where the problem lies. I wrote it based on your configuration

![image](https://github.com/user-attachments/assets/a4772740-8713-4dc1-a190-5f6e9dd291ef)

**Comment by ssrlive** [comment]
![image](https://github.com/user-attachments/assets/701575f6-c73f-4c40-94eb-99ba87da3705)

**Comment by ssrlive** [comment]
![image](https://github.com/user-attachments/assets/c4fa6484-1eac-499d-86fc-5bf745634bbe)

**Comment by chenxudong2020** [comment]
![image](https://github.com/user-attachments/assets/b9c11e40-c54c-48a4-b054-e9cb94450150)
It's not related to that. I tried the same mistake with other tunnel_path. All the brushes in the pictures above are covering my domain name

**Comment by chenxudong2020** [comment]
Do you mean to change 127.0.0.1 to a domain name?

**Comment by chenxudong2020** [comment]
![image](https://github.com/user-attachments/assets/e46a15e0-d15b-472f-8664-1dcea5348832)
![image](https://github.com/user-attachments/assets/3967fb5d-9337-44da-84c4-5cac408b1be5)
I have made the changes, but the same mistake still exists. The hidden domain names in the picture are all mine

**Comment by ssrlive** [comment]
![image](https://github.com/user-attachments/assets/93ee6f62-9ecb-4af2-82fe-16e55f3bcdd0)

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/overtls?tab=readme-ov-file#installation-script-with-caddy

**Comment by chenxudong2020** [comment]
> https://github.com/ShadowsocksR-Live/overtls?tab=readme-ov-file#installation-script-with-caddy



> https://github.com/ShadowsocksR-Live/overtls?tab=readme-ov-file#installation-script-with-caddy

I used a one click installation script and looked at the configuration file. It's basically the same as mine, except for tunnel_math. I have multiple others that are no different, but I still reported an error using Overtls win

**Comment by ssrlive** [comment]
Because the overtls.dll file shiped by ssrwin does not use the dll included in the latest 0.2.37 version.

**Comment by chenxudong2020** [comment]
I replaced this DLL file and it can be used now, but it still reports authentication failure because the locally launched one does not have authentication, which may be due to authentication information before the browser cache

**Comment by chenxudong2020** [comment]
I have time to modify SSRWin, and later Docker can be migrated from nginx to Caddy

**Comment by chenxudong2020** [comment]
If you have time to modify SSRWin, Docker can be migrated from nginx to Caddy later

**Comment by ssrlive** [comment]
latest release have contained overtls.dll of 0.2.27 version.
