### ISSUE TITLE
overtls + tun2proxy services on Win, sometims can't access internet, restart services needed

### ISSUE THREAD

**Issue by videosoftware** [ShadowsocksR-Live/overtls#66]
I run overtls and tun2proxy as Windows services but sometimes I can't access the internet

their status is running

after stopping/starting one or two services I can access the internet again. It doesn't seem to be a problem on the server side

How can I fix this?

**Comment by zheshinicheng** [comment]
我觉得你可以尝试一下 出现这个问题的时候电脑的DHCP分配的地址是不是发生了变化，可能是这类原因吧

**Comment by ssrlive** [comment]
so, you'd better never run tun2proxy as a service.

**Comment by videosoftware** [comment]
I would try running tun2proxy from a script to see the difference

**Comment by videosoftware** [comment]
I run tun2proxy all day long, and I hardly use any services inside the wall

**Comment by ssrlive** [comment]
![image](https://github.com/user-attachments/assets/0c854235-84f8-4371-a222-5f0d201b881d)

**Comment by videosoftware** [comment]
Thanks

I set the startup type of tun2proxy to manual to see if that makes a difference

**Comment by videosoftware** [comment]
Maybe I didn't describe the problem clearly

Both services were running normally at the beginning, but sometimes I suddenly couldn't access the internet

**Comment by chenxudong2020** [comment]
I think you should give this software a try https://github.com/chenxudong2020/overtlsclient Download the folder inside and use single box to split the files

**Comment by videosoftware** [comment]
Thanks, I'll give it a try

**Comment by ssrlive** [comment]
This situation is very common, what you can do is, kill tun2proxy, and then run tun2proxy.

**Comment by videosoftware** [comment]
Now that I understand,

It seems like it would be best to create a script for tun2proxy, put a shortcut on desktop, and when I lose internet access, just close the info window and re-run the script

**Comment by ssrlive** [comment]
I have add an option `--exit-on-fatal-error` for `tun2proxy`, now you can use it with `tun2proxy` running as a windows service.

https://github.com/tun2proxy/tun2proxy/commit/c991006f4c932c96625f1c7be2e834364bd43f0c

https://blog.csdn.net/qq_25837039/article/details/121832037

![img](https://i-blog.csdnimg.cn/blog_migrate/72e673ebb15eee675ae751fcdde84523.png)
