### ISSUE TITLE
ipv6和udp中继

### ISSUE THREAD

**Issue by zheshinicheng** [ShadowsocksR-Live/overtls#8]
您好，请问这您这个项目支持ipv6和udp中继吗。
SSRoT我用了半年多效果非常好，就是udp中继效果不好。经常报_client_0.0.0.0错误。

**Comment by ssrlive** [comment]
得益於 rust 語言的現代特性，你提到的這些問題都已完美解決。

**Comment by zheshinicheng** [comment]
太棒了，我将把SSRoT迁移到overtls。感谢您的工作！

**Comment by zheshinicheng** [comment]
你好，我在使用overtls转发基于UDP的DNS请求时出现问题，我不确定是程序有问题还是配置有问题。
  我使用 dnsmasq 处理本地DNS解析查询 ，使用iptables防火墙将UDP和TCP 流量定向hev-socks5-tproxy（一个防火墙透明代理软件），最后将hev-socks5-tproxy接收到的流量发送到overtls客户端提供的本地socks5服务器端口。实现无感知的防火墙透明代理。
  在我的配置下其他的TCP和UDP流量都能正确的被处理，唯独UDP DNS流量无法处理。（因为VPS没有ipv6地址，所以客户端的主机禁用了ipv6）
**这是客户端的配置文件，（已抹去隐私信息。）**
`{
    "method": "none",
    "password": "puViSBbbK8NEsdiNLW",
    "tunnel_path": "/QwYxX8Tz3qnMpqNczK9/",

    "client_settings": {
        "disable_tls": false,
        "server_host": "*********",
        "server_port": 443,
        "server_domain": "********",
        "cafile": "/mnt/overtls/ca_bundle.crt",
        "listen_host": "127.0.0.1",
        "listen_port": 3080
    }
}
`
**使用时能正确转发其他类型的UDP流量，但是使用转发UDP** DNS流量时经常出现以下日志输出：
`[2023-03-28T13:30:32Z TRACE overtls::udprelay] [UDP] waiting for incoming packet
[2023-03-28T13:30:32Z TRACE overtls::udprelay] [UDP] incoming packet 127.0.0.1:37310 -> 8.8.8.8:53 51 bytes
[2023-03-28T13:30:32Z TRACE overtls::udprelay] [UDP] waiting for incoming packet
[2023-03-28T13:30:32Z TRACE overtls::udprelay] [UDP] send to remote 127.0.0.1:37310 -> 8.8.8.8:53 65 bytes
[2023-03-28T13:30:33Z TRACE overtls::udprelay] [UDP] 127.0.0.1:37310 <- 8.8.8.8:53 length 55
[2023-03-28T13:30:33Z TRACE overtls::udprelay] [UDP] skip feedback packet 8.8.8.8:53 -> 127.0.0.1:37310
[2023-03-28T13:30:33Z TRACE overtls::udprelay] [UDP] feedback to incoming 127.0.0.1:37310
[2023-03-28T13:30:37Z TRACE overtls::udprelay] [UDP] incoming packet 127.0.0.1:37310 -> 8.8.8.8:53 51 bytes
`
**而使用TCP** DNS时可以成功解析域名:
`[2023-03-28T13:50:19Z TRACE overtls::client] 127.0.0.1:51920 -> 8.8.8.8:53 tunnel establishing
[2023-03-28T13:50:20Z TRACE overtls::client] 127.0.0.1:51920 -> 8.8.8.8:53 length 53
[2023-03-28T13:50:20Z TRACE overtls::client] 127.0.0.1:51920 <- 8.8.8.8:53 length 57
[2023-03-28T13:50:20Z TRACE overtls::client] 127.0.0.1:51920 -> 8.8.8.8:53 incoming closed
[2023-03-28T13:50:20Z TRACE overtls::client] 127.0.0.1:51920 disconnected
`
**使用dig** 测试udp dns解析时，无法成功：
![dnsmasq+dig+udp](https://user-images.githubusercontent.com/94763882/228261100-35ba0a37-c570-42d7-a8b7-bfdf94f6cc2e.PNG)
**使用dig** 测试tcp dns解析时，成功解析：
![dnsmasq+dig+tcp](https://user-images.githubusercontent.com/94763882/228261328-4d1b06f2-ef14-498c-99ed-89cf0e99f4e1.PNG)
**测试时overtls的日志输出：**
![overtls_log](https://user-images.githubusercontent.com/94763882/228261522-20fb658f-56d0-4cad-87f2-5ab57a623bf8.PNG)

**Comment by ssrlive** [comment]
如果你想在 linux 下實現透明代理，你使用 https://github.com/blechschmidt/tun2proxy 是最好的，這幾天才新鮮出爐，與 overtls 是很好的搭檔。

**Comment by zheshinicheng** [comment]
好的，我去找点资料看看。谢谢您的解答！

**Comment by ssrlive** [comment]
嗨 @zheshinicheng 問你一個技術問題, 雖然有點丟臉但我臉皮厚. 當 udp 中繼進來后, 也夾雜著 dns 查詢數據包, 代理軟件客戶端是否可以不加處理地通過 websocket 協議(tcp包) 發送到遠端代理服務器, 遠端代理服務端再不加甄別地當成普通 udp 數據包發送到 目標 dns 服務器. 這麽做能否得到正確的 dns 查詢結果? 就是這裏的流程我一直沒搞清楚, 導致我軟件在處理 dns 查詢轉發這一塊總是稀里糊塗, 效果不佳. 希望得到你的反饋.


這裏就是 本地客戶端收到 應用軟件 傳入的 udp 數據包后, 無腦發送到 遠端服務器的地方.

https://github.com/ShadowsocksR-Live/overtls/blob/5fc8bc46f5f497b5deda4c39b3d2926626ff3752/src/udprelay.rs#L171-L184


這裏就是 遠程服務器 無腦轉發 udp 數據包的地方.

https://github.com/ShadowsocksR-Live/overtls/blob/5fc8bc46f5f497b5deda4c39b3d2926626ff3752/src/server.rs#L283-L289

以及這裏的遠程服務端的實質性 處理流程
https://github.com/ShadowsocksR-Live/overtls/blob/5fc8bc46f5f497b5deda4c39b3d2926626ff3752/src/server.rs#L383

**Comment by zheshinicheng** [comment]
**您好，我刚下班。收到您的邮件十分意外，因为我不是程序员。甚至英语也非常的差。如果您觉得中间写的毫无头绪的话，可以直接看最后加粗字体**
  您制作的overTLS我一直在使用，但是因为我不是计算机程序员无法给您提供专业的意见。只能向您描述我使用overTLS搭建透明网关是如何避免DNS UDP的转发出问题的。

我使用[hev-socks5-tproxy](https://github.com/heiher/hev-socks5-tproxy)，hev-socks5-tproxy是一款在iptables/nftables防火墙将流量重定向到Socks5服务器的开源软件。我在Linux终端的iptables的mangle表的PREROUTING链，将目标地址是53端口的UDP数据包重定向到hev-socks5-tproxy提供的DNS转发端口，由hev-socks5-tproxy转发到到上游域名服务器。这是hev-socks5-tproxy的配置文件：
`socks5:
  port: 1080
  address: 127.0.0.2
  udp: 'udp'

tcp:
  port: 1086
  address: '127.0.0.2'

udp:
  port: 1086
  address: '127.0.0.2'

dns:
  port: 1085
  address: '127.0.0.2'
  upstream: 127.0.0.1

misc:
   task-stack-size: 32768
   udp-recv-buffer-size: 10485760
   log-file: /run/GFW-log/socks5-tproxy-ipv4.log
   log-level: warn
   pid-file: /run/GFW-log/socks5-tproxy-ipv4.pid
`
  它的配置文件是YML格式，下面的socks5节是OverTLS提供的本地Socks5服务器端口，也就是将流量透明的转发到OverTLS的本地服务端口。
`socks5:
  port: 1080
  address: 127.0.0.2
  udp: 'udp'
`
其中有DNS配置节，提供一个iptables/nftables 的TPROXY模块透明转发UDP流量的地址和端口：address: '127.0.0.2' port: 1085。而upstream是UDP的转发的目的端口，我的配置文件中的upstream: 127.0.0.1是转发到本地的Dnsmasq端口127.0.0.1:53。由Dnsmasq匹配一定规则（GFW）的域名通过HTTPS的域名服务器进行解析（使用dnsmasq的server和ipset选项，将域名解析结果的地址加入ipset，并由iptables/nftables匹配。
这是‘iptables -t mangle -S’输出的规则：
`-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N OUTPUT_MARK
-N PREROUTING_TPROXY
-A PREROUTING -m set --match-set overTLS_ipv4 dst -j PREROUTING_TPROXY
-A PREROUTING ! -d 192.168.1.4/32 -i enp1s0 -p udp -m udp --dport 53 -j TPROXY --on-port 1085 --on-ip 127.0.0.2 --tproxy-mark 0x29a/0xffffffff
-A OUTPUT -o enp1s0 -m mark ! --mark 0x29a -m set --match-set overTLS_ipv4 dst -j OUTPUT_MARK
-A OUTPUT_MARK -p udp -j MARK --set-xmark 0x29a/0xffffffff
-A OUTPUT_MARK -p tcp -j MARK --set-xmark 0x29a/0xffffffff
-A PREROUTING_TPROXY -p udp -j TPROXY --on-port 1086 --on-ip 127.0.0.2 --tproxy-mark 0x29a/0xffffffff
-A PREROUTING_TPROXY -p tcp -j TPROXY --on-port 1086 --on-ip 127.0.0.2 --tproxy-mark 0x29a/0xffffffff
`
`-A PREROUTING -m set --match-set overTLS_ipv4 dst -j PREROUTING_TPROXY`这行表示将overTLS_ipv4匹配的地址走透明代理。
`-A PREROUTING ! -d 192.168.1.4/32 -i enp1s0 -p udp -m udp --dport 53 -j TPROXY --on-port 1085 --on-ip 127.0.0.2 --tproxy-mark 0x29a/0xffffffff`**这里是将DNS UDP的流量重定向到hev-socks5-tproxy后转发到上游DNS**
**我很努力的组织语言向您描述我的解决方案，但是我觉得我写的好像一堆臭屁**
**我的方案绕过了使用UDP进行GFWlist域名解析，实际上大多数公共互联网服务的网络端口是标准端口（IANA分配的），也许您可以通过DNS的标准端口号53/UDP去另外处理DNS流量。hev-socks5-tproxy是C编写的，由于您之前的SSRoT也是由C编写的。我认为您对C语言应该非常熟悉，或许您可以参考一下他的源码，它里面有重定向DNS数据包的源码。**
**我非常乐意配合您改进OverTLS，但我确实是不会编程。另外您的TCP连接的DNS在透明代理中是正常的，就是延迟大概是ping延迟的2倍（ICMP 2Rtt)**
**如果能配合您改进OverTLS的话，我将十分荣幸。感谢您让我们用上了自由的网络！**

**Comment by zheshinicheng** [comment]
刚刚抽了根香烟思考了一下，您也许可以在客户端和服务端加一个小的模块专门处理DNS数据包，将客户端目标端口是53/UDP的数据包重新包装一下成为JSON或其它类型的http协议的数据包。通过WebSocket传输到服务端后，由服务端重新拆包转换成UDP发送到公共域名解析服务器。我想强调的是大多数公共互联网服务都是通过IANA的标准端口提供服务。
  如果您认为添加一个模块太复杂的话，可以通过某些方式（防火墙或透明网关）将DNS查询的UDP的流量重定向到某些使用HTTPS Over DNS转发域名查询的软件。据我所知有很多提供这些功能的软件。例如：[https_dns_proxy](https://github.com/aarond10/https_dns_proxy)。

**Comment by ssrlive** [comment]
OK. 感謝反饋. 我去研究源碼.

**Comment by zheshinicheng** [comment]
好的，如果有新的问题或新的版本发布请在这个问题通知我。感谢您的工作！

**Comment by ssrlive** [comment]
現在將服務端的 dns 查詢的目標服務器強行改寫成 8.8.8.8 了， 你有空測試一下， dns 查詢走代理會怎麼樣？

https://github.com/ShadowsocksR-Live/overtls/blob/bd9c228c668b7118555ac2b7f5c8c221ed97ffb2/src/server.rs#L395-L409

**Comment by zheshinicheng** [comment]
大哥你这效率杠杠的，我这就去编译测试一下！

**Comment by zheshinicheng** [comment]
您好，刚刚已经对v0.2.0版本进行了测试，因为重新安装了一部虚拟机搭建测试，所以导致到现在才测试完。显然您已经解决了服务端转发DNS查询的问题，**但是客户端还是有些问题**。因为我没有编程经验，所以把测试情况告知您，方便您修复！
![20230710003611](https://github.com/ShadowsocksR-Live/overtls/assets/94763882/ac08bf64-d490-482a-92ce-a050a5717795)
**请注意，图片左边两个终端是服务器的，右边两个终端是客户机的。**
**请注意左下图中dns.google是8.8.8.8 公共服务器的域名，而为了隐藏服务器真实地址，我在/etc/hosts文件中把服务器地址改成域名localhost。服务端很显然已经正确转发了DNS请求，并且收到了DNS返回的A类型响应。**
**左边的tcpdump窗口中只监听到发送到8.8.8.8的DNS请求，并没有收到响应**
`skip freedback packet 8.8.8.8:53 ->127.0.0.1:58722`
**这应该是问题的所在，也就是客户端没正确处理源端口是53的DNS响应包**
也就是这里！
https://github.com/ShadowsocksR-Live/overtls/blob/bd9c228c668b7118555ac2b7f5c8c221ed97ffb2/src/udprelay.rs#L171-L189

**Comment by zheshinicheng** [comment]
抱歉，上面代码贴错了
https://github.com/ShadowsocksR-Live/overtls/blob/bd9c228c668b7118555ac2b7f5c8c221ed97ffb2/src/udprelay.rs#L174-L195

**Comment by ssrlive** [comment]
我弄了 [幾個工具](https://github.com/ssrlive/socks5-impl/releases) 用於測試 socks5 代理. 

裏邊的工具 dns-query 看起來表現正常. 其中 `-t` 代表使用 `TCP` 協議, `-v` 代表走代理, `-p` 代表代理的監聽端口. 四種排列組合看起來都沒問題.

你那裏如果不用 `tcpdump` 而是實際跑一跑 瀏覽器之類的看看, 能否正常使用?

```bash
C:>d:\dns-query.exe -d google.com
172.217.160.110

C:>d:\dns-query.exe -d google.com -t
172.217.160.110

C:>d:\dns-query.exe -d google.com -v -p 127.0.0.1:1080
142.250.72.238

C:>d:\dns-query.exe -d google.com -v -p 127.0.0.1:1080 -t
142.250.72.238
```

**Comment by zheshinicheng** [comment]
老哥，我这会正鼓捣着呢。主要我这是透明网关代理，涉及iptables dnsmasq hev-socks5-tproxy一大堆软件配置。所以测试起来比较复杂。我得确定问题才能给您肯定的答复！

**Comment by zheshinicheng** [comment]
**服务端tcpdump监听命令
`tcpdump** -i any "port 53" -v`
结果：

> 19:25:57.384687 eth0  Out IP (tos 0x0, ttl 64, id 59513, offset 0, flags [DF], proto UDP (17), length 56)
>    localhost.44844 > dns.google.53: 23448+ A? github.com. (28)
>19:25:57.390659 eth0  In  IP (tos 0x0, ttl 123, id 61589, offset 0, flags [none], proto UDP (17), length 72)
  >  dns.google.53 > localhost.44844: 23448 1/0/0 github.com. A 20.27.177.113 (44)


客户端命令：`./dns-query -d github.com -v -p 192.168.8.1:1080`
返回结果：
>20.27.177.113

这是OverTLS v0.2.0的日志输出：
> [2023-07-10T11:29:48Z INFO  overtls::udprelay] [UDP] listen on 192.168.8.1:45036
[2023-07-10T11:29:48Z TRACE overtls::udprelay] [UDP] waiting for incoming packet
[2023-07-10T11:29:48Z TRACE overtls::udprelay] [UDP] incoming packet 192.168.8.1:47876 -> 8.8.8.8:53 28 bytes
[2023-07-10T11:29:48Z TRACE overtls::udprelay] [UDP] waiting for incoming packet
[2023-07-10T11:29:48Z TRACE overtls::udprelay] [UDP] DNS query package 192.168.8.1:47876 -> 8.8.8.8:53
[2023-07-10T11:29:48Z TRACE overtls::udprelay] [UDP] 192.168.8.1:47876 <- 8.8.8.8:53 length 58
[2023-07-10T11:29:48Z TRACE overtls::udprelay] [UDP] skip feedback packet 8.8.8.8:53 -> 192.168.8.1:47876
[2023-07-10T11:29:48Z TRACE overtls::udprelay] [UDP] feedback to incoming 192.168.8.1:47876
[2023-07-10T11:29:48Z TRACE overtls::udprelay] [UDP] listener 192.168.8.1:45036 closed with Ok(())
[2023-07-10T11:29:48Z TRACE overtls::client] 192.168.8.1:46610 disconnected

**dns-query得到的是正确的解析结果，因为是从远程的服务器返回的。也许是我的透明网关代理的某些重定向策略有问题，我去检查一下我的透明网关代理配置**

**Comment by zheshinicheng** [comment]
补充一下说明
TCP/IP层的协议逻辑链接的数据传输是; (src addr : src port) -> (dst addr : dst port)
而在逻辑连接对端回复时将 addr:port 反转使用。
例子：
简化TCP连接建立过程
```
client packet 192.168.1.2:4598 -> 142.251.42.196:443(https://www.google.com)
server packet 142.251.42.196:443(https://www.google.com)  -> 192.168.1.2:4598
```

**Comment by zheshinicheng** [comment]
也许我们从一开始思路就是错误的！用标准的Socks5代理基于UDP的DNS协议是很难实现的。需要对程序端和客户端进行一些非标准的改造。
```
05:55:19.157166 ip: (tos 0x0, ttl 64, id 58997, offset 0, flags [DF], proto UDP (17), length 68)
    192.168.1.3.48796 > 8.8.8.8.53: [udp sum ok] 1271+ [1au] AAAA? wx.qlogo.cn. ar: . OPT UDPsize=1232 (40)
05:55:19.241232 ip: (tos 0x0, ttl 255, id 41, offset 0, flags [none], proto UDP (17), length 226)
    127.0.0.1.43832 > 192.168.1.3.48796: [udp sum ok] UDP, length 198
```
这是一对由 _OverTLS_ + _透明代理_ 处理的 DNS的查询和响应，发起DNS查询的 `192.168.1.3:48796` 客户端拒绝接收   `127.0.0.1.43832 > 192.168.1.3.48796` 返回的响应，只有地址是 `8.8.8.8:53`时客户端才会认为是正确的响应。
我想应该是在客户端单独绑定一个UDP监听端口用于转发DNS查询，透明代理时将DNS流量引导到监听端口 由远端的服务器转发解析后由本地客户端的UDP监听端口发送到查询的发起端口，避免**NAT**导致的ip地址和端口的转换。
如果您还会继续对该问题进行改进的话，请重新打开这个问题。谢谢您！@ssrlive 

![2019040133](https://github.com/ShadowsocksR-Live/overtls/assets/94763882/a0c42fd5-203d-4156-9e8d-25a809bb3972)

**Comment by ssrlive** [comment]
看了這個視頻 https://www.bilibili.com/video/BV1Kg411475R/ 。打算寫一個 dns 代理服務，將本機的 所有 dns 查詢都引導到 socks5 服務上去。這個主題就可以翻篇了。

**Comment by zheshinicheng** [comment]
是的，你是正确的！HTTPS over DNS速度比您软件里面已有的UDP over DNS转发延迟大概增加3 ~5 倍，所以我认为制作您说的dns代理时应该使用overtls的udp转发，在dns客户端代理提供一个UDP监听端口转发查询到overtls server解析。而把本机查询流量引导到dns代理服务则是操作系统配置或透明代理的工作。 
![97_1](https://github.com/ShadowsocksR-Live/overtls/assets/94763882/994191d0-eef2-48c2-adda-8a99366f7d38)

**Comment by ssrlive** [comment]
dns2socks 工具已經搞完, 現在 dns 那些齷齪事兒全部可以肉眼可見了. 你有空測試一下.

https://github.com/ssrlive/socks5-impl/releases 

```
Proxy server to routing DNS query to SOCKS5 server

Usage: dns2socks.exe [OPTIONS]

Options:
  -l, --listen-addr <address:port>        Listen address [default: 0.0.0.0:53]
  -d, --dns-remote-server <address:port>  Remote DNS server address [default: 8.8.8.8:53]
  -s, --socks5-server <address:port>      SOCKS5 proxy server address [default: 127.0.0.1:1080]
  -u, --username <user name>              User name for SOCKS5 authentication
  -p, --password <password>               Password for SOCKS5 authentication
  -v, --verbose                           Verbose mode
  -h, --help                              Print help
  -V, --version                           Print version
```

**Comment by zheshinicheng** [comment]
好的！感谢您！

**Comment by zheshinicheng** [comment]
**您好，我在使用您的工具转发后DNS请求都能成功转发并获得请求结果。您已经成功解决了这个问题！**
使用命令   `dig @127.0.0.1 -p 5859 www.github.com `分别测试以下两个不同的远程域名服务器地址：
```
./dns2socks -l 127.0.0.1:5859 -d 8.8.8.8:53 -s 127.0.0.2:1080 -v
./dns2socks -l 127.0.0.1:5859 -d 1.1.1.1:53 -s 127.0.0.2:1080 -v
```
服务端结果：
```
localhost.57662 > one.one.one.one.53: [bad udp cksum 0x085c -> 0xf1f4!] 18835+ [1au] A? github.com. ar: . OPT UDPsize=1232 [COOKIE b3b9e95bec5af646] (51)
    one.one.one.one.53 > localhost.57662: [udp sum ok] 18835 q: A? github.com. 1/0/1 github.com. [13s] A 20.27.177.113 ar: . OPT UDPsize=1232 (55)
```

```
 localhost.57662 > dns.google.53: [bad udp cksum 0x166a -> 0xd91d!] 58169+ [1au] A? github.com. ar: . OPT UDPsize=1232 [COOKIE bd9bada2f2da440f] (51)
    dns.google.53 > localhost.57662: [udp sum ok] 58169 q: A? github.com. 1/0/1 github.com. [1m] A 20.27.177.113 ar: . OPT UDPsize=512 (55)
```

**Comment by ssrlive** [comment]
好了. 這事兒終於結束了. 感謝你的測試幫助.

**Comment by zheshinicheng** [comment]
在将dns2socks作为nsmasq的上游服务器时出现一些Err之类的错误，但是能正常使用。貌似也没有负面影响。您的dns2socks通过overtls的原生接口转发DNS请求，延迟在我的机器上是80ms~90ms,我的远程服务器ping延时是80ms~120ms。**简直太棒了！感谢您的辛勤工作！**
![Uploading dnsmasq.png…]()

**Comment by ssrlive** [comment]
這些錯誤是不礙事的, 那是 DNS 查詢返回的 CNAME 等類型的值. 轉換不成 IP 地址. 我偷懶就統統認定為錯誤. 不影響使用. 只是給好事者隨意觀察用的. 睡個好覺.

**Comment by zheshinicheng** [comment]
好的，谢谢您！晚安

**Comment by ssrlive** [comment]
將 dns2socks 加了一個參數 cache 現在可以緩存查詢結果了. 查詢應該會提速不少.

https://github.com/ssrlive/socks5-impl/releases

**Comment by zheshinicheng** [comment]
这是一个很棒的功能！感谢您！
另外我在`socks5-impl`打开了一个issue，希望您回复一下。
https://github.com/ssrlive/socks5-impl/issues/1#issue-1806526240
